; default user settings
[Graphics]
Screen_Width = Default
Screen_Height = Default

[Window]
Display_Mode = Fullscreen
FPS = 60

[Player1 Controls]
Left = key, a
Right = key, d
Jump = key, w
Down = key, s
Sprint = key, left shift
Punch = key, space
Block = key, e
Activate = key, f

[Player2 Controls]
Left = key, left
Right = key, right
Jump = key, up
Down = key, down
Sprint = key, right shift
Punch = key, return
Block = key, backspace
Activate = key, [0]