; default user settings
[Graphics]
Screen_Width = Default
Screen_Height = Default

[Window]
Display_Mode = Fullscreen
FPS = 60

[Player1 Controls]
Left = key, A
Right = key, D
Jump = key, W
Down = key, S
Sprint = key, LSHIFT
Punch = key, SPACE
Activate = key, E

[Player2 Controls]
Left = key, LEFT
Right = key, RIGHT
Jump = key, UP
Down = key, DOWN
Sprint = key, RSHIFT
Punch = key, RETURN
Activate = key, KP0